name: main
on: [push, pull_request]
#on:
#  push:
#    branches-ignore:
#      - main
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8.1'
          cache: 'pip' # caching pip dependencies
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
#      - name: Setup Python venv
#        run: |
#          poetry config virtualenvs.create true --local
#          poetry config virtualenvs.in-project true --local
#      - uses: actions/cache@v3
#        name: Python Poetry venv cache
#        with:
#          path: ./.venv
#          key: venv-${{ hashFiles('poetry.lock') }}
      - name: Install dependencies
        working-directory: .
        run: |
          poetry install
      - name: Run flake8, isort and black checks
        working-directory: .
        run: |
          poetry run flake8 .
          poetry run isort --check .
          poetry run black --check .
#      - name: Run mypy
#        run: poetry run mypy paita --explicit-package-bases
      - name: Run Tests
        run: poetry run pytest --cov-report=xml
#      - name: Upload Coverage to Codecov
#        uses: codecov/codecov-action@v1